spring.application.name=underapp-api
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET:change-me-in-env}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.jpa.hibernate.ddl-auto=update
